/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * User model w/o password
 * @export
 * @interface PatchedUserDetails
 */
export interface PatchedUserDetails {
    /**
     * 
     * @type {number}
     * @memberof PatchedUserDetails
     */
    readonly pk?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof PatchedUserDetails
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetails
     */
    readonly email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetails
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserDetails
     */
    lastName?: string;
}

/**
 * Check if a given object implements the PatchedUserDetails interface.
 */
export function instanceOfPatchedUserDetails(value: object): value is PatchedUserDetails {
    return true;
}

export function PatchedUserDetailsFromJSON(json: any): PatchedUserDetails {
    return PatchedUserDetailsFromJSONTyped(json, false);
}

export function PatchedUserDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'pk': json['pk'] == null ? undefined : json['pk'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
    };
}

export function PatchedUserDetailsToJSON(json: any): PatchedUserDetails {
    return PatchedUserDetailsToJSONTyped(json, false);
}

export function PatchedUserDetailsToJSONTyped(value?: Omit<PatchedUserDetails, 'pk'|'email'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
    };
}

export const PatchedUserDetailsPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
    username: {
        maxLength: 150,
        pattern: '/^[\\w.@+-]+$/',
    },
    firstName: {
        maxLength: 150,
    },
    lastName: {
        maxLength: 150,
    },
}

